# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - app-agrogest

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - name: Restore NuGet packages
        run: dotnet restore GestAgro.sln

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish API
        run: dotnet publish GestAgro.API/GestAgro.API.csproj -c Release -o ${{env.DOTNET_ROOT}}/api-app

      - name: Install EF Core Tools
        run: dotnet tool install --global dotnet-ef --version 9.0.9
        
      - name: Run EF Core Migrations
        run: dotnet ef database update --project GestAgro.Infrastructure/GestAgro.Infrastructure.csproj --startup-project GestAgro.API/GestAgro.API.csproj
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}

      - name: Upload API artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-artifact
          path: ${{env.DOTNET_ROOT}}/api-app

      # Carrega o artefato do Blazor
      - name: Upload Blazor artifact
        uses: actions/upload-artifact@v4
        with:
          name: blazor-artifact
          path: ${{env.DOTNET_ROOT}}/blazor-app

  # --- JOB 1: FAZ O DEPLOY DA API ---
  deploy-api:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact for API
        uses: actions/download-artifact@v4
        with:
          name: api-artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_39524B2A4ECC4AD8B32A1F80B8515125 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BE1F4BE3572D4FEE85B7E0B5AFFE7D58 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EBD910ED06A745ECBB0CAE46D68F5ED5 }}

      - name: Deploy API to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-agrogest'
          slot-name: 'Production'
          package: .
          
